### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by annca** [six7/figma-assets-generator#6]
Thanks for the script! The docs don't mention support for PDF extension but I tried it and it does technically export. However, the exported size doesn't match the size of my component's frame. When I export manually, the size is correct. But via the script, the size matches the bounds of my vector paths. Do you know why?

**Comment by six7** [comment]
Hey @annca 

I took a look at the code, right now I filter out all components on the Icons page and use these component nodes to export, in your case youd like the frames around these components to be exported.

How would you want it to work, I could make it so the script looks for specific layer names (e.g. "-"-export" at the end, and uses these to export.

**Comment by annca** [comment]
I looked at the Figma API and saw that they have a property `use_absolute_bounds` which is `false` by default. Ideally, if I set this to `true`, it would work how I need it. However, I tested this on their website and it still didn't give me the expected result. I send a support request to Figma team about this. I'll let you know once I hear back.

**Comment by annca** [comment]
I heard back from Figma support. They did seem to confirm they have a bug here, but no ETA. When they do fix it though, it would be good to be able to customize this property in your script.

**Comment by six7** [comment]
Will do! Perhaps a workaround for now would be to set the fill of the component to white - not ideal, I know..

**Comment by annca** [comment]
Good news! Figma team has said that they fixed the bug. I tested with their API and it seems to work. So now `use_absolute_bounds` needs to be added to options in your script. By default, it's `false`, but I will need to set it `true`. Let me know when this would be doable.

**Comment by six7** [comment]
Great! I [added ](https://github.com/six7/figma-assets-generator/commit/b22e251d779c776405b0663d9d9f31684e409620) that and published `1.2.0`!

I tried it locally and it works! 👍

**Comment by six7** [comment]
Closing this issue - feel free to reopen if it doesn't work!
